name: Update promos
on:
  schedule: [{cron: "0 6 * * *"}]   # 06:00 UTC
  workflow_dispatch:                # przycisk „Run workflow”
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run fetch script
        run: python .github/scripts/fetch_promos.py
      - name: Commit & push if changed
        run: |
          git config --global user.name  'promo-bot'
          git config --global user.email 'bot@example.com'
          git add promos.json
          git diff --cached --quiet || (git commit -m "auto-update promos" && git push)
