name: Daily promotions update
on:
  schedule:
    - cron: '0 6 * * *'   # codziennie o 6:00 UTC
  workflow_dispatch:        # ręczne uruchomienie też możliwe

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch promotions
        run: |
          # demo-dane z realnych sieciówek (możesz podpiąć API)
          cat > index.html << 'EOF'
          <!doctype html>
          <html lang="pl">
          <head>
            <meta charset="utf-8">
            <title>Promoszop – aktualne promocje</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
          </head>
          <body class="bg-light">
            <div class="container py-4">
              <h1 class="mb-4 text-center">Promocje na $(date '+%d.%m.%Y')</h1>
              <table class="table table-striped">
                <thead>
                  <tr><th>Sklep</th><th>Produkt</th><th>Cena&nbsp;promo</th><th>Stara&nbsp;cena</th><th>Rabat</th></tr>
                </thead>
                <tbody>
                  <tr><td>Biedronka</td><td>Pierś z kurczaka 1 kg</td><td>9,99 zł</td><td>14,99 zł</td><td>-33 %</td></tr>
                  <tr><td>Lidl</td><td>Czekolada Milka 100 g</td><td>2,99 zł</td><td>4,99 zł</td><td>-40 %</td></tr>
                  <tr><td>Kaufland</td><td>Jogurt naturalny 400 g</td><td>1,69 zł</td><td>2,49 zł</td><td>-32 %</td></tr>
                  <tr><td>Aldi</td><td>Pomidory malinowe 500 g</td><td>4,99 zł</td><td>6,99 zł</td><td>-29 %</td></tr>
                  <tr><td>Netto</td><td>Mleko UHT 3,2 % 1 l</td><td>2,49 zł</td><td>3,19 zł</td><td>-22 %</td></tr>
                  <tr><td>Dino</td><td>Płatki owsiane 500 g</td><td>2,99 zł</td><td>4,29 zł</td><td>-30 %</td></tr>
                </tbody>
              </table>
              <p class="text-center text-muted mt-4">Aktualizacja: $(date '+%d.%m.%Y %H:%M')</p>
            </div>
          </body>
          </html>
          EOF

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update promocje $(date '+%d.%m.%Y')"
          git push
